---
title: "SMARTIES T-matrix with defined accuracy"
author: "baptiste"
date: today
engine: knitr
---

This example script for SMARTIES calculates T-matrices with a predefined accuracy, and exports them in `.tmat.h5` format. The script is available as standalone script [smarties_advanced.m](/smarties/smarties_advanced.m).

SMARTIES provides some functions to estimate the maximum multipolar order and number of quadrature points required to reach a desired accuracy. We choose here to fix the relative accuracy to $10^{-8}$ for the orientation-averaged extinction cross-section, which results in higher $l_\text{max}$ values for larger and/or more elongated spheroids. Note that in some cases SMARTIES may fail to achieve the requested accuracy, in which case a manual adjustment of the convergence parameters may help.


```{octave, eval=FALSE}
path(pathdef); % clear previous path changes
addpath(genpath('~/Documents/nano-optics/smarties/'));
addpath(genpath('~/Documents/nano-optics/easyh5/'));
clearvars;

%% example

% requested precision (OA Cext)
accuracy = 1e-8;

% prolate Au spheroid in water
% semi-axes a=b=20nm, c=40nm
wavelength = 400:50:800; wavelength = wavelength(:); 
Nl = length(wavelength);
epsilon=epsAu(wavelength);
medium=1.33;

% constant simulation parameters
stParams.a=20;
stParams.c=40;

% internal options
stOptions.bGetR = false;
stOptions.Delta = 0;
stOptions.NB = 0; % NB will be estimated automatically
stOptions.bGetSymmetricT = false;
stOptions.bOutput = false; % verbosity
```

We first estimate the maximum convergence parameters required

```{octave, eval=FALSE, echo=-1}
%% first, figure out the maximum N's needed

globalN = 1;
globalnNbTheta = 1;

% loop over wavelengths
for i=1:Nl
    stParams.k1=medium*2*pi/wavelength(i);
    stParams.s=sqrt(epsilon(i)) / medium;
    % Estimated convergence params
    [N, nNbTheta] = sphEstimateNandNT(stParams, stOptions, accuracy);
    stParams.N=N; stParams.nNbTheta=nNbTheta;
    % Increase params to test accuracy
    stParams2=stParams;
    stParams2.N=stParams2.N+5;
    stParams2.nNbTheta=stParams2.nNbTheta+5;

    [stCoa, stT] = slvForT(stParams,stOptions);
    [stCoa2, stT2] = slvForT(stParams2,stOptions);

    if(stOptions.bOutput)
        fprintf('Convergence testing... lambda = %.5g\n', wavelength(i));
        fprintf('<Cext> = %.10g,   relative error: %.2g\n', stCoa.Cext, abs(stCoa.Cext./stCoa2.Cext-1));
        fprintf('<Csca> = %.10g,   relative error: %.2g\n', stCoa.Csca, abs(stCoa.Csca./stCoa2.Csca-1));
        fprintf('<Cabs> = %.10g,   relative error: %.2g\n', stCoa.Cabs, abs(stCoa.Cabs./stCoa2.Cabs-1));
    end

    if(abs(stCoa.Cext./stCoa2.Cext-1) > 1.1*accuracy)
        % try once more

        stParams=stParams2;
        stParams.N=stParams2.N+5;
        stParams.nNbTheta=stParams2.nNbTheta+5;
        [stCoa, stT] = slvForT(stParams,stOptions);
        [stCoa2, stT2] = slvForT(stParams2,stOptions);

        if(abs(stCoa.Cext./stCoa2.Cext-1) > 1.1*accuracy)

            warning(fprintf('requested precision was not achieved for  = %.5g\n', wavelength(i)))
        end

    end

    globalN = max(globalN, stParams.N);
    globalnNbTheta = max(globalnNbTheta, stParams.nNbTheta);
end
```

Next, we redo the calculations for all wavelengths with these fixed parameters, and collect the results in an array suitable for export to `.tmat.h5` format.

```{octave, eval=FALSE, echo=-1}
%% now redo calculations for all wavelengths with these fixed params

stParams.N=globalN; stParams.nNbTheta=globalnNbTheta;
    
% allocate 3D array for all results
qmax = 2*(globalN*(globalN + 1) + globalN );
tmatrix = zeros(length(wavelength), qmax, qmax);

for i=1:Nl
    stParams.k1=medium*2*pi/wavelength(i);
    stParams.s=sqrt(epsilon(i)) / medium;


    [stCoa, stT] = slvForT(stParams,stOptions);

    [T, u, up] = expand_tmat(stT, qmax); % tmatrix elements and indices
    ind = sub2ind(size(tmatrix),u*0+i, u, up); % linear index in 3D array
    tmatrix(ind) =  T(:,7) + 1i*T(:,8);

end
% keep note of which elements are known to be exact zeros
analytical_zeros = true(qmax,qmax);
analytical_zeros(sub2ind(size(analytical_zeros), u, up)) = false;
```

Finally, we export the data into HDF5.

```{octave, eval=FALSE, echo=-1}
%% data to export
epsilon = struct(...
    'embedding', medium^2, 'particle', epsilon, 'embedding_name', 'H2O, Water', ...
    'embedding_keywords', 'non-dispersive', 'embedding_reference', 'constant', ...
    'material_name', 'Au, Gold', 'material_reference', 'Au from Johnson and Christy 1972',...
    'material_keywords', 'dispersive, plasmonic');

geometry = struct('radiusxy', stParams.a, 'radiusz', stParams.c);

computation = struct('description', 'Computation using SMARTIES, a numerically robust EBCM implementation for spheroids', ...
    'accuracy', 1e-10, 'Lmax', stParams.N, 'Ntheta', stParams.nNbTheta, ...
    'analytical_zeros', analytical_zeros);

comments = struct('name', 'Au prolate spheroid in water',...
    'description', 'Computation using SMARTIES, a numerically robust EBCM implementation for spheroids',...
    'keywords', 'gold, spheroid, ebcm', 'script', [mfilename '.m']);

tmatrix_hdf5('smarties_advanced.tmat.h5', tmatrix, wavelength, epsilon,...
              geometry, computation, comments)
```

<!-- export the code into standalone file -->
`r invisible(knitr::purl(xfun::with_ext(knitr::current_input(), "qmd"),output=xfun::with_ext(knitr::current_input(), "m")))`

Output file: [smarties_advanced.tmat.h5](/smarties/smarties_advanced.tmat.h5)

